[firebase_config]
apiKey = "AIzaSyDUMMY-KEY-FOR-AUTH"
authDomain = "https://www.google.com/search?q=histopai-dummy.firebaseapp.com"
projectId = "histopai-hackathon"
storageBucket = "https://www.google.com/search?q=histopai-dummy.appspot.com"
messagingSenderId = "1234567890"
appId = "1:1234567890:web:abcdef1234567890"

app_id = "histopai-hackathon"
initial_auth_token = "SIMULATED_AUTH_TOKEN_FOR_USER_LOGIN"
gemini_api_key = "DUMMY_GEMINI_KEY"